Tema/Models/Joc.cs
using System.ComponentModel.DataAnnotations;

namespace Tema.Models
{
    public class Joc
    {
        public int Id { get; set; }
        public string? Titlu { get; set; }

        [DataType(DataType.Date)]
        public DateTime DataLansarii { get; set; }
        public string? Gen { get; set; }
        public decimal Pret { get; set; }
    }
}

Tema/Controllers/JocsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Tema.Data;
using Tema.Models;

namespace Tema.Controllers
{
    public class JocsController : Controller
    {
        private readonly TemaContext _context;

        public JocsController(TemaContext context)
        {
            _context = context;
        }

        // GET: Jocs
        public async Task<IActionResult> Index(string sortOrder, string searchString,string currentFilter, int pageNumber=1)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            

            var jocuri = from s in _context.Joc
                           select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                jocuri = jocuri.Where(s => s.Titlu.Contains(searchString)
                                     );
            }

            switch (sortOrder)
            {
                case "name_desc":
                    jocuri = jocuri.OrderByDescending(s => s.Titlu);
                    break;
                case "Date":
                    jocuri = jocuri.OrderBy(s => s.DataLansarii);
                    break;
                case "date_desc":
                    jocuri = jocuri.OrderByDescending(s => s.DataLansarii);
                    break;
                default:
                    jocuri = jocuri.OrderBy(s => s.Titlu);
                    break;
            }

            int pageSize = 3;
            //returneaza lista paginta pentru paginare
            return View(await PaginatedList<Joc>.CreateAsync(jocuri.AsNoTracking(), pageNumber , pageSize));

            /* return _context.Joc != null ?
                          View(await _context.Joc.ToListAsync()) :
                          Problem("Entity set 'TemaContext.Joc'  is null.");*/
        }

     


        // GET: Jocs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Joc == null)
            {
                return NotFound();
            }

            var joc = await _context.Joc
                .FirstOrDefaultAsync(m => m.Id == id);

            if (joc == null)
            {
                return NotFound();
            }
            // aici faci
            var model1Data = joc;// Get data for Model1
          
            var model3Data = new Reviews();
            var model2Data = new Reviews();
            List<Reviews> p=new List<Reviews>(); // Get data for Model2
            
           p= await _context.Reviews
        .Where(r => r.IdJoc == id)
        .ToListAsync();

            //p.Add(model2Data);
            IEnumerable<Reviews> r = p;
            /*returneaza model triplu : Jocuri IEnumerable de reviews pentru afisare lista de reviewuri si
            review pentru adaugare review*/
            var combinedData = (model1Data, r,model3Data);

            return View(combinedData);

        }
        //functie adaugare review
        [HttpPost]
        public async Task<IActionResult> AddReview(int id, string Autor, string Review)
        {
            if (string.IsNullOrEmpty(Autor) || string.IsNullOrEmpty(Review))
            {
                ModelState.AddModelError("", "Please enter both Autor and Review.");
                return RedirectToAction("Details", new { id });
            }

            var review = new Reviews
            {
                IdJoc = id,
                Autor = Autor,
                Review = Review,
                DataCompletarii = DateTime.Now
            };

            _context.Reviews.Add(review);
            await _context.SaveChangesAsync();
            //redirectioneaza catre details dupa ce adauga review
            return RedirectToAction("Details", new { id });
        }

        // GET: Jocs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jocs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titlu,DataLansarii,Gen,Pret")] Joc joc)
        {
            if (ModelState.IsValid)
            {
                _context.Add(joc);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(joc);
        }

        // GET: Jocs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Joc == null)
            {
                return NotFound();
            }

            var joc = await _context.Joc.FindAsync(id);
            if (joc == null)
            {
                return NotFound();
            }
            
            return View(joc);
        }

        // POST: Jocs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titlu,DataLansarii,Gen,Pret")] Joc joc)
        {
            if (id != joc.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(joc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JocExists(joc.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            
         
            return View(joc);
        }

        // GET: Jocs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Joc == null)
            {
                return NotFound();
            }

            var joc = await _context.Joc
                .FirstOrDefaultAsync(m => m.Id == id);
            if (joc == null)
            {
                return NotFound();
            }

            return View(joc);
        }

        // POST: Jocs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Joc == null)
            {
                return Problem("Entity set 'TemaContext.Joc'  is null.");
            }
            var joc = await _context.Joc.FindAsync(id);
            if (joc != null)
            {
                _context.Joc.Remove(joc);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JocExists(int id)
        {
          return (_context.Joc?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Tema/Views/Jocs/Create.cshtml
@model Tema.Models.Joc

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Joc</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titlu" class="control-label"></label>
                <input asp-for="Titlu" class="form-control" />
                <span asp-validation-for="Titlu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataLansarii" class="control-label"></label>
                <input asp-for="DataLansarii" class="form-control" />
                <span asp-validation-for="DataLansarii" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gen" class="control-label"></label>
                <input asp-for="Gen" class="form-control" />
                <span asp-validation-for="Gen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pret" class="control-label"></label>
                <input asp-for="Pret" class="form-control" />
                <span asp-validation-for="Pret" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Tema/Views/Jocs/Delete.cshtml
@model Tema.Models.Joc

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Joc</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titlu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titlu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataLansarii)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataLansarii)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pret)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pret)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Tema/Views/Jocs/Details.cshtml
<!-- Model triplu -->
@model (Tema.Models.Joc, IEnumerable<Tema.Models.Reviews>, Tema.Models.Reviews)

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Joc</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item1.Titlu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item1.Titlu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item1.DataLansarii)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item1.DataLansarii)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item1.Gen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item1.Gen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item1.Pret)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item1.Pret)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Item1.Id">Edit</a>
    <a asp-action="Index">Back to List</a>
</div>


<table class="table">
    <thead>
        <tr>
            <th>
              Autor
            </th>
            <th>Review </th>
            <th>
              Data
            </th>
         
        </tr>
    </thead>
    <tbody>
        <!-- Afisare review-uri -->
        @foreach (var item in Model.Item2)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Autor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Review)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataCompletarii)
                </td>
              
                
            </tr>
        }
    </tbody>
</table>

<!-- Adaugare reviewuri -->
<form asp-action="AddReview" asp-route-id="@Model.Item1.Id" method="post">
    <div class="form-group">
        <label for="Autor" class="control-label">Autor</label>
        <input type="text" id="Autor" name="Autor" class="form-control" />
    </div>

    <div class="form-group">
        <label for="Review" class="control-label">Review</label>
        <textarea id="Review" name="Review" style="height:100px;" class="form-control"></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Add Review</button>
</form>

Tema/Views/Jocs/Edit.cshtml
@model Tema.Models.Joc

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Joc</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titlu" class="control-label"></label>
                <input asp-for="Titlu" class="form-control" />
                <span asp-validation-for="Titlu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataLansarii" class="control-label"></label>
                <input asp-for="DataLansarii" class="form-control" />
                <span asp-validation-for="DataLansarii" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gen" class="control-label"></label>
                <input asp-for="Gen" class="form-control" />
                <span asp-validation-for="Gen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pret" class="control-label"></label>
                <input asp-for="Pret" class="form-control" />
                <span asp-validation-for="Pret" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Tema/Views/Jocs/Index.cshtml
<!-- Model lista paginata -->
@model PaginatedList<Tema.Models.Joc>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by name: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Titlu</a>

            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Data Lansarii</a>
            </th>
            <th>
                Gen
            </th>
            <th>
                Pret
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titlu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataLansarii)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pret)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

<div class="container">
    <ul class="paginare" style="list-style-type: none;">
        @for (var pge = 1; pge <= Model.TotalPages; pge++)
        {
            <li class="item pagina" style="display: inline;">
                <a class="linkpagina" asp-controller="Jocs" asp-action="Index" asp-route-pageNumber="@pge">@pge</a>
            </li>
        }
    </ul>
</div>

<style>
    /* Styles for pagination */
    .paginare li {
        margin-right: 5px;
    }

    .linkpagina {
        padding: 5px 10px;
        background-color: #eaeaea;
        color: #333;
        text-decoration: none;
        transition: background-color 0.3s ease;
    }

        .linkpagina:hover {
            background-color: #333;
            color: #fff;
        }
</style>

    